version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "Installing backend dependencies"
      - npm install
  build:
    commands:
      - echo "Building backend"
      - npm run build
  post_build:
    commands:
      - echo "Post build phase"
      - mkdir -p /tmp/deployment/backend
      - cp -R * /tmp/deployment/backend/

artifacts:
  files:
    - /tmp/deployment/backend/**/*